site_name: jugaad-boards
site_description: jugaad Boards Documentation
site_author: Abhijit Bose (0x3508a)

theme:
  name: material
  font: false
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode (Default)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: light green
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

copyright: >-
  Copyright &copy; 1998 - 2023 
  <a href="https://github.com/0x3508a" targe="_blank" rel="noopener">Abhijit Bose (0x3508a)</a>. 
  All rights reserved.
  <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/" targe="_blank" rel="noopener"><code style="background-color: indigo;color: white;">SPDX: CC-BY-NC-ND-4.0</code></a>

extra:
  generator: false
  consent:
    title: Cookie consent
    actions:
      - accept
      - reject
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      # linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - def_list
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - abbr
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
