name: 'Build jugaad_samd_ard'

env:
  TAG_NAME: ${{ github.ref_name }}

## Trigger
on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

## Jobs to Work On
jobs:
  arduino-samd-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Build script
        run: |
          cd samd-arduino
          ./build.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Archive
          path: ${{ github.workspace }}/artifacts/**/*
          retention-days: 5
